#!/usr/bin/env bash

tmp="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/tmp"

setup() {
  version='0.3.0'
  os="$( uname -s | tr '[:upper:]' '[:lower:]' )"
  arch='amd64'

  mkdir -p "$tmp"

  if [[ ! -e "${tmp}/consul" ]]; then
    echo
    echo "Downloading consul into $tmp"
    echo

    name="${version}_${os}_${arch}.zip"

    pushd "$tmp" &>/dev/null

    curl -LO "https://dl.bintray.com/mitchellh/consul/${name}"

    echo
    unzip "$name"
    echo

    rm -f "$name"

    popd &>/dev/null
  fi
}

start_server() {
  id="$1"; shift
  data="${tmp}/data/${id}"

  rm -fr "$data"
  mkdir -p "$data"

  "${tmp}/consul" agent \
    -data-dir="$data" \
    -node="node${id}" \
    -dc=dc1 \
    -bind="127.0.0.${id}" \
    -client="127.0.0.${id}" \
    -pid-file="${tmp}/consul_${id}.pid" \
    $@ \
    &> "${tmp}/consul_${id}.log" &
}

start() {
  setup; stop &>/dev/null

  echo 'Starting server id 1 (bootstrap)'

  start_server 1 -bootstrap -server

  for id in {2..3}; do
    echo "Starting server id $id"

    start_server $id
  done
}

stop() {
  for id in {1..3}; do
    if [[ -f "${tmp}/consul_${id}.pid" ]]; then
      pid="$( cat "${tmp}/consul_${id}.pid" )"
      echo "Killing server id $id pid $pid"
      kill "$pid"
    fi

    rm -rf "${tmp}/consul_${id}."* "${tmp}/data/${id}"
  done
}

case $1 in
  start) shift; start "$@" ;;
  stop) shift; stop "$@" ;;
  *) echo "Unknown command: $1" ;;
esac
