#!/usr/bin/env bash

mkdir -p ./tmp

cd ./tmp

rm -fr ./data
mkdir -p ./data

if [[ ! -f ./consul ]]; then
  name="0.3.0_$( uname -s | tr '[:upper:]' '[:lower:]' )_amd64.zip"
  if [[ ! -f "$name" ]]; then
    wget "https://dl.bintray.com/mitchellh/consul/${name}"
  fi
  unzip *.zip
fi
