name: Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  npm:
    name: npm
    runs-on: ubuntu-latest

    environment:
      name: npm
      url: https://www.npmjs.com/package/consul

    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install
        run: pnpm install

      - name: Publish
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
